name: Distributed Platform CI 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  

jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Docker Compose 
      run: |
        docker compose up -d --build
        echo "Waiting for services to be intialized.."
        sleep 15

    - name: Check Container Health
      run: |
        docker compose ps
        curl -f http://localhost:3000/metrics || exit 1
    
    - name: Install k6
      run: |
        sudo apt-get update
        sudo snap install k6

    - name: Push Database Schema
      run: |
        docker compose exec -T ingestion-api npx prisma db push
    
    - name: Seed Database for Load Test
      run: |
        docker compose exec -T postgres psql -U webhook_user -d webhook_platform -c "INSERT INTO tenants (id, name, created_at) VALUES ('b3b8c386-8809-407b-8919-72c1cbaea15e', 'CI Load Test Tenant', NOW()) ON CONFLICT DO NOTHING;"    
        docker compose exec -T postgres psql -U webhook_user -d webhook_platform -c "INSERT INTO endpoints (id, tenant_id, url, secret, created_at) VALUES ('c4c9d497-9910-518c-9020-83d2dcbfa26f', 'b3b8c386-8809-407b-8919-72c1cbaea15e', 'https://httpstat.us/200', 'test_secret', NOW()) ON CONFLICT DO NOTHING;"
    
    - name: Run load test with k6
      run: |
        k6 run tests/load_tests.js

    - name: Capture logs
      if: failure()
      run: docker compose logs --tail=100
      
